#!/usr/bin/env python3
from flask import Flask, request, jsonify, render_template, Response, redirect, url_for
import ollama
import json
import markup
import os

app = Flask(__name__)

ai_content = ""
model = "dolphin-llama3"
history = [
    {"role": "system", "content": ai_content},
]

def load_chat_history(unique_id):
    try:
        with open(f"chat_history/{unique_id}.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return [{"role": "system", "content": ai_content}]

def save_chat_history(unique_id, history):
    os.makedirs("chat_history", exist_ok=True)
    with open(f"chat_history/{unique_id}.json", "w") as f:
        json.dump(history, f)

@app.route("/")
def index():
    if len(history) > 1:
        history.clear()
    characters = json.load(open("characters.json"))
    return render_template("index.html", characters=characters)

@app.route("/chat/<unique_id>")
def chat(unique_id):
    characters = json.load(open("characters.json"))
    ai = next((character for character in characters if character["unique_id"] == unique_id), None)
    if ai:
        global history
        history = load_chat_history(unique_id)
        ai_content = ai["description"]
        history[0]["content"] = ai_content
        name = ai["name"]
        previous_chats = [{"unique_id": c["unique_id"], "name": c["name"]} for c in characters]
        return render_template("chat.html", history=history, name=name, previous_chats=previous_chats)
    else:
        return "Character not found", 404

@app.route("/send", methods=["POST"])
def send():
    message = {"role": "user", "content": request.json["message"]}
    history.append(message)
    unique_id = request.args.get("unique_id")

    def generate():
        full_response = ""
        buffer = ""
        for response in ollama.chat(model=model, messages=history, stream=True):
            chunk = response["message"]["content"]
            buffer += chunk
            # Check if buffer contains an even number of '*'
            if buffer.count('*') % 2 == 0:
                full_response += buffer
                buffer = markup.markup(buffer)
                yield buffer
                buffer = ""
        full_response += buffer
        yield buffer
        full_response = markup.markup(full_response)
        m = {"role": "assistant", "content": full_response}
        history.append(m)
        save_chat_history(unique_id, history)

    return Response(generate(), mimetype="text/event-stream")

@app.route("/history", methods=["GET"])
def get_history():
    if len(history) > 1:
        return jsonify(history[1:])
    return jsonify([])

@app.route("/chat/static/js/app.js")
def app_js():
    return redirect(url_for('static', filename='js/app.js'))

if __name__ == "__main__":
    app.run(debug=True, threaded=True)